#spring.application.name=ShowImages

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://db:5432/slideshowdb
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop


